name: Generate Assets
on:
  workflow_dispatch:
    inputs:
      versionString:
       type: string
       required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: AdamRaichu/mcaddon-package-workflow/.github/workflows/main.yml@v1
        with:
          pack_name: example_pack
          pack_type: 0
          target_path: ./builds/${{ inputs.versionString }}
          bp_path: ./behavior_pack
          rp_path: ./resource_pack
      - name: commit changes
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generate \`${{inputs.versionString}}\` assets"
          git push