name: Generate Assets
on:
  workflow_dispatch:
    inputs:
      versionString:
       type: string
       required: true
jobs:
  generate:
    uses: AdamRaichu/mcaddon-package-workflow/.github/workflows/main.yml@trial-1
    with:
      pack_name: example_pack
      pack_type: 0
      target_path: ./builds/${{ inputs.versionString }}
      bp_path: ./bp
      rp_path: ./rp